# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/ENEL373/Project/mine/main_project.cache/wt [current_project]
set_property parent.project_path D:/ENEL373/Project/mine/main_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  D:/ENEL373/Project/mine/main_project.srcs/sources_1/new/reg_4_en.vhd
  D:/ENEL373/Project/mine/main_project.srcs/sources_1/new/ALU.vhd
  D:/ENEL373/Project/mine/main_project.srcs/sources_1/new/tristate_8_buf.vhd
  D:/ENEL373/Project/mine/main_project.srcs/sources_1/new/reg_8.vhd
  D:/ENEL373/Project/mine/main_project.srcs/sources_1/new/control_unit.vhd
  D:/ENEL373/Project/mine/main_project.srcs/sources_1/new/led_mux.vhd
  P:/Downloads/my_divider.vhd
  D:/ENEL373/Project/mine/main_project.srcs/sources_1/new/main_project.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/ENEL373/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files D:/ENEL373/Nexys4DDR_Master.xdc]


synth_design -top main -part xc7a100tcsg324-3


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
